{% set name = "ledger" %}
{% set version = "3.3.1" %}
{% set sha256 = "c18341020552fa221203afdf0c0eade1bfa9aa4b7e1ab82a0e456c06b56d1ce4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ledger/ledger/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win or osx or py<38]
  run_exports:
    - {{ pin_subpackage("ledger") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - boost
    - gmp
    - mpfr
    - utfcpp
    - gettext # optional
    - libedit # optional
    - python # optional
    - doxygen # docs
    - graphviz # docs
    - texinfo # docs
  run:
    - boost
    - gmp
    - mpfr
    - utfcpp
    - gettext # optional
    - libedit # optional
    - python # optional

test:
  commands:
    - ledger | grep {{ version }}

about:
  home: https://www.ledger-cli.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Double-entry accounting system with a command-line reporting interface
  description: |
    Ledger is a powerful, double-entry accounting system that is accessed from the
    UNIX command-line. Ledger, begun in 2003, is written by John Wiegley and
    released under the BSD license. It has also inspired several ports to other
    languages.
  doc_url: https://www.ledger-cli.org/docs.html
  dev_url: https://github.com/ledger/ledger

extra:
  recipe-maintainers:
    - twrightsman
